name: C/C++ CI

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/benesim/actions-test/gcc:latest
    - name: Push docker image
      run: docker push docker.pkg.github.com/benesim/actions-test/gcc:latest
