name: C/C++ CI

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: BeneSim
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/benesim/actions-test/gcc:latest
    - name: Push docker image
      run: docker push docker.pkg.github.com/benesim/actions-test/gcc:latest
  build:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: BeneSim
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: compile
      run: |
        mkdir build
        docker container run --rm -v $(pwd):/app -w /app/build docker.pkg.github.com/benesim/actions-test/gcc:latest cmake ..
        docker container run --rm -v $(pwd):/app -w /app/build docker.pkg.github.com/benesim/actions-test/gcc:latest make
    - name: Archive executable
      uses: actions/upload-artifact@v1
      with:
        name: actions-test
        path: build/artifact-test
