name: C/C++ CI

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: BeneSim
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/benesim/actions-test/gcc:latest
    - name: Push docker image
      run: docker push docker.pkg.github.com/benesim/actions-test/gcc:latest
  build:
    runs-on: ubuntu-latest
    needs: docker
    container:
      image: docker.pkg.github.com/benesim/actions-test/gcc:latest
    steps:
        - uses: actions/checkout@v1
        - name: Run CMake
          run: |
              mkdir build
              cd build
              cmake ..
        - name: Build
          run: |
              make



